#!/usr/bin/ruby
require 'rss'
require 'open-uri'
require 'optparse'
require 'liquid'
require 'cgi'
require 'digest/md5'
require 'digest/sha1'

module TextFilter
	def spaces_to_underscores(input)
		input.gsub(/\s/, '_')
	end

	def urlencode(input)
		CGI::escape(input)
	end

	def md5(input)
		Digest::MD5.hexdigest(input)
	end

	def sha1(input)
		Digest::SHA1.hexdigest(input)
	end
end
Liquid::Template.register_filter(TextFilter)

class TabCastFeed
attr_reader :url, :feed, :template

	def initialize(url, format)
		@url = url
		@items = RSS::Parser.parse(url, false).items
		@template = Liquid::Template.parse(unescape(format))
	end

	def formatted
		string = ""
		@items.each do |i|
			vars = Hash.new
			vars['utime'] = i.pubDate.strftime('%s') if i.pubDate
			vars['title'] = i.title.chomp if i.title
			vars['enclosure_url'] = i.enclosure.url if i.enclosure && i.enclosure.url
			vars['itunes_author'] = i.itunes_author if i.itunes_author
			vars['author'] = i.author if i.author

			string += @template.render(vars)
		end
		string
	end

	private

	def unescape(string)
		string.gsub!('\t', "\t")
		string.gsub!('\n', "\n")
		string
	end
end

options = {}

optparse = OptionParser.new do|opts|
	#set default
	options[:format] = '{{utime}}\t{{title | spaces_to_underscores}}\t{{enclosure_url}}\n'

	opts.banner = "Usage: tabcast [-f FORMATSTRING] file1 file2 ...\n(FORMATSTRING is assumed to be '#{options[:format]}' unless specified)
	
FORMATSTRING is a Liquid template (http://liquidmarkup.org/) that will be rendered once for each feed item.
			
The following variables are available to the template:
{{ utime }}           			-> The pubDate time of the feed item as a Unix timestamp.
{{ title }}           			-> The title of the feed item with new lines removed.
{{ enclosure_url}}     			-> The full URL of the feed item's
{{ author }}, {{ itunes_author }}	-> Just what it says on the tin.
			
The following filters are available to the template:
`whitespace_to_underscores` does exactly what it sounds like.
`md5` `and sha1` likewise.
`urlencode` is pretty self-explanatory too.
	
In addition, the following sequences are escaped to the equivalent literal characters:" +
'
`\t`     -> literal tab
`\n`     -> literal newline

'

	opts.on( '-f', '--format FORMATSTRING', 'Output lines with FORMATSTRING' ) do |format|
		options[:format] = format
	end

	opts.on( '-d', '--delimiter DELIMITER', 'Use some other than tabs as the field delimiter' ) do |delimiter|
		options[:format] = "{{utime}}#{delimiter}{{title | spaces_to_underscores}}#{delimiter}{{enclosure_url}}" + '\n';
	end

	opts.on( '-h', '--help', 'Show usage.' ) do
		puts opts
		exit
	end
end

optparse.parse!

ARGV.each do |url|
	feed = TabCastFeed.new(url, options[:format])
	puts feed.formatted
end
